### ISSUE TITLE
Support Redshift Credentials

### ISSUE THREAD

**Issue by dave-connors-3** [GtheSheep/terraform-provider-dbt-cloud#121]
[Spec from Postman](https://www.postman.com/dbtlabs/workspace/dbt-cloud-api-documentation/request/14183654-606ac802-fe09-46c7-a5cb-35ed7c791982)

for completeness, we should support Redshift credentials

**Comment by GtheSheep** [comment]
@dave-connors-3 completed by #131 ? 🎉

**Comment by b-per** [comment]
@dave-connors-3
