### ISSUE TITLE
Docs - Examples with `<...>` do not render properly

### ISSUE THREAD

**Issue by b-per** [GtheSheep/terraform-provider-dbt-cloud#125]
It looks like the examples in the docs that contain `<...>` don't render properly. This section of the code gets replaced by an empty string.

Examples on https://registry.terraform.io/providers/GtheSheep/dbt-cloud/latest/docs/resources/dbt_cloud_repository
- The 2 places with the URL on how to get the GH application ID
- The description of `remote_url`: _"or / for Gitlab"_

**Comment by GtheSheep** [comment]
Wow good spot, I guess they may just need escaping?

**Comment by GtheSheep** [comment]
```- `remote_url` (String) Git URL for the repository or \<Group>/\<Project> for Gitlab```
can be escaped like this, see https://registry.terraform.io/tools/doc-preview

**Comment by GtheSheep** [comment]
As for the code bit, declaring it as `console` seems to render it correctly
