### ISSUE TITLE
Missing `github_installation_id` optional argument on `dbt_cloud_repository` docs

### ISSUE THREAD

**Issue by alexsweet** [GtheSheep/terraform-provider-dbt-cloud#129]
The argument `github_installation_id` is mentioned on [line 14](https://github.com/GtheSheep/terraform-provider-dbt-cloud/blob/cfc415840215842a56f9fe4dd396d0b0b4f775a5/docs/resources/dbt_cloud_repository.md?plain=1#L14) of dbt_cloud_repository.md

However, there isn't an optional argument for the `github_installation_id` specified in the docs;
https://github.com/GtheSheep/terraform-provider-dbt-cloud/blob/cfc415840215842a56f9fe4dd396d0b0b4f775a5/docs/resources/dbt_cloud_repository.md?plain=1#L37-L41

**Comment by GtheSheep** [comment]
Weird, can see it on line 62 of pkg/resources/repository.go, will check

**Comment by GtheSheep** [comment]
Ah ok i see the issue here, fix incoming
