### ISSUE TITLE
Bug on redeploy for the Snowflake Environment Credential 

### ISSUE THREAD

**Issue by Stevedow99** [GtheSheep/terraform-provider-dbt-cloud#144]
Hey @GtheSheep!

My name is Steve Dowling I work at dbt Labs. I love the provider package. I'm in the middle of using it to make a bunch of modules that others using dbt Cloud can leverage to easily do their deployments (Hopefully can link back the docs when done).

I noticed one small bug when doing re-deployments of the Snowflake Environment Credential resource. Whenever you do a redeploy it only updates the schema value in the environment credential regardless of what you are trying to update. 

Figured the easiest way to explain is to make a loom video on it:

[Terraform dbt Cloud Provider Snowflake Environment Credential Bug Loom Video](https://www.loom.com/share/177a52ae132640d18d6aa617de1acfc0)

Thanks!

**Comment by b-per** [comment]
This was a quick one. I created a PR for it.

**Comment by GtheSheep** [comment]
Thanks so much @b-per !!
