### ISSUE TITLE
package not available for darwin_arm64 on registry.terraform.io

### ISSUE THREAD

**Issue by bcgalvin** [GtheSheep/terraform-provider-dbt-cloud#43]
First I'd just like to say that I'm super excited about the work being done here, thanks a ton for putting in the effort. 

I think it's possible to get around the terraform registry issue by cloning/building locally but I'm hoping to wrap this in [cdktf](https://github.com/hashicorp/terraform-cdk) and am not quite sure if the fix will work there. Do you have plans to release the provider for other platforms?

**Comment by GtheSheep** [comment]
Hey! Thanks for spotting this, I actually hadn't clocked that this platform wasn't supported, I'll take a look into it in the next day or so and hopefully get it added!

**Comment by bcgalvin** [comment]
awesome thanks!

**Comment by bcgalvin** [comment]
I was able to fix it locally without a problem - I bundled this + the snowflake provider in a cdktf library and they're on [npm](https://www.npmjs.com/package/cdktf-dbt-snowflake) / [pypi](https://pypi.org/project/cdktf-dbt-snowflake/) now. 

Planning on tinkering with this provider over the weekend and should have some code examples in there by Monday. Thanks again for your work on this @GtheSheep!

**Comment by GtheSheep** [comment]
@bcgalvin - hey, looks like my releaser was just running an old Go Version that deprecated darwin/amd64, I'll bump the version and then this should be supported going forward 👌
