### ISSUE TITLE
Example for snowflake credentials rotation?

### ISSUE THREAD

**Issue by ernestoongaro** [GtheSheep/terraform-provider-dbt-cloud#54]
Is it possible to upload new snowflake credentials into an environment with this project?

**Comment by GtheSheep** [comment]
Hey @ernestoongaro - you should be able to use the Snowflake Credential resource combined with the Environment data source/ resource to do this by providing the credential_id to the environment I believe.
Credential: https://registry.terraform.io/providers/GtheSheep/dbt-cloud/latest/docs/resources/dbt_cloud_snowflake_credential
Env: https://registry.terraform.io/providers/GtheSheep/dbt-cloud/latest/docs/resources/dbt_cloud_environment

Is it a new or existing env specifically? With that I should be able to add an example for this.
Thanks for this!

**Comment by ernestoongaro** [comment]
Thanks Gary! It would be for an existing environment, if you have an
example that would help me a lot!

**Comment by GtheSheep** [comment]
Hey @ernestoongaro - In order to add the credential to an existing environment, you would need to import the environment to Terraform such that it can be managed as a resource (I think), in which case, a full example would be something like:
```
terraform {
  required_providers {
    dbt = {
      source  = "GtheSheep/dbt-cloud"
      version = "0.0.75"
    }
  }
}

provider "dbt" {
  account_id = <ACCOUNT ID>
  token      = "<TOKEN>"
}

data "dbt_cloud_project" "test_project" {
  project_id = <project ID>
}

resource "dbt_cloud_snowflake_credential" "new_credential" {
  project_id  = data.dbt_cloud_project.test_project.project_id
  auth_type   = "password"
  num_threads = 16
  schema      = "DATA"
  user        = "user"
  password    = "password"
}

resource "dbt_cloud_environment" "test_environment" {
  dbt_version   = "1.0.1"
  name          = "test"
  project_id    = data.dbt_cloud_project.test_project.project_id
  type          = "deployment"
  credential_id = dbt_cloud_snowflake_credential.new_credential.credential_id
}
```
of course, I'd recommend passing the passwords at apply/ plan time as variables rather than storing in code, they're marked as sensitive in the provider, hope this helps 😸

**Comment by ernestoongaro** [comment]
Wow thanks so much! Will give it a go once I have the other pieces in place. Should this be saved into your examples folder somehow @GtheSheep?

**Comment by GtheSheep** [comment]
@ernestoongaro good call! I've added the credential and environment as relative files in the examples folder 😺

**Comment by ernestoongaro** [comment]
That's awesome! Thank you

(closed in https://github.com/GtheSheep/terraform-provider-dbt-cloud/commit/4bdacab58516349ea37f70b23afacac895426230 and https://github.com/GtheSheep/terraform-provider-dbt-cloud/commit/858f78db4d0532c2b1078de1cc5b56661ae6a1b5)
