### ISSUE TITLE
Add support for custom host_url

### ISSUE THREAD

**Issue by octavio-melo** [GtheSheep/terraform-provider-dbt-cloud#55]
Thanks very much for this provider, it is highly useful. I would like to suggest adding a third option of  `host_url` to the [client](https://github.com/GtheSheep/terraform-provider-dbt-cloud/blob/main/pkg/dbt_cloud/client.go#L12
) so users with custom url (`https://cloud.<company>.getdbt.com`) can also use it. Thanks and regards!

**Comment by GtheSheep** [comment]
Ah, I didn't know this existed, thanks! Will get it added 👌

**Comment by GtheSheep** [comment]
#56

**Comment by GtheSheep** [comment]
Released
