### ISSUE TITLE
Adding environment variables

### ISSUE THREAD

**Issue by Bryan-Meier** [GtheSheep/terraform-provider-dbt-cloud#61]
I have a question in regards to imports. I don't see that the documentation shows anything about import existing resources. Has imports been implemented and they just are not in the docs?

**Comment by GtheSheep** [comment]
Hey, yeah imports exist for all resources using their IDs, anything in specific you'd like to import?
I used the docs generator plugin terraform provides, but yeah I should add docs as imports don't come for free 😔

**Comment by Bryan-Meier** [comment]
No worries on the lack of docs for imports. I'm just glad that imports exists. :smile: I will give it a try. I would really love to be able to import and create environment variables. In the dbt Cloud API there is currently no way I have found to get the environment variables out of dbt Cloud. I am hoping v4 of their API will allow for this.

**Comment by GtheSheep** [comment]
Ahh ok, I've not actually used env vars in dbt cloud, but I'll create a dummy one and see if the api for them works when I get a chance 👌

**Comment by GtheSheep** [comment]
Hey, so there are endpoints for read/update/delete/create for env vars, should be pretty easy to add to the provider

**Comment by Bryan-Meier** [comment]
That add for us, would awesome. We use a ton of environment variables (env vars) in dbt Cloud and the manual setup/management of those is the biggest time killer for us. The addition of keypair authentication for credentials and the env var management would solve virtually all our current problems. If there is a way that you think I can help, please feel free to reach out. Thanks again!

**Comment by GtheSheep** [comment]
@Bryan-Meier - whoops, forgot about this branch 😅 released in v0.0.85
