### ISSUE TITLE
Adding Snowflake token auth

### ISSUE THREAD

**Issue by Bryan-Meier** [GtheSheep/terraform-provider-dbt-cloud#62]
@GtheSheep, I am curious if you will be implementing other authentication types besides "password" for credentials?  I am asking because we use keypair in Snowflake and thus use that in our dbt Cloud credentials.

**Comment by GtheSheep** [comment]
Happy to 😀 tbh most of what's here is driven by my own use cases, but great to add more if useful!

**Comment by Bryan-Meier** [comment]
Totally get it. I would be doing the same if I was in your position.

**Comment by Bryan-Meier** [comment]
Are you storing your passwords for your credentials in a variable and gabbing that variable when you create the credential or are you currently storing the password in the code? I know we should never store password info in code. So I am wondering what the other options are.

**Comment by GtheSheep** [comment]
#68

**Comment by GtheSheep** [comment]
Added to v0.0.83
