### ISSUE TITLE
Databricks connection type

### ISSUE THREAD

**Issue by hadiel05** [GtheSheep/terraform-provider-dbt-cloud#78]
Is there a way to use this provider with the databricks connection on a project? looking through the code looks like only snowflake and bigquery is supported? https://github.com/GtheSheep/terraform-provider-dbt-cloud/blob/86c89283157915277916ae315beb11fe5ea9db7a/pkg/resources/connection.go#L14

**Comment by GtheSheep** [comment]
Hey, there isn't currently, happy to try to add it though!
Will check out if there's a free tier to test against or something 👌

**Comment by hadiel05** [comment]
> Hey, there isn't currently, happy to try to add it though! Will check out if there's a free tier to test against or something 👌

That will be great! and yes there should be a free tier for you to test out

**Comment by hadiel05** [comment]
@GtheSheep wanted to check if there is an update on this request?

**Comment by GtheSheep** [comment]
Hey, yes I've been working on it, no luck with testing it tho, will update you here when I merge the resource/ related release 🙂

**Comment by hadiel05** [comment]
@GtheSheep do you happen to have an ETA on this would also like for Redshift?

**Comment by GtheSheep** [comment]
Hey, yeah sorry things have dropped off a bit lately (especially the connectors that require sign ups to test), am at coalesce this week but will continue working on things next week so you'll see the PRs 👌
