### ISSUE TITLE
Connection options for Postgres, Redshift, and AlloyDB 

### ISSUE THREAD

**Issue by tanjinP** [GtheSheep/terraform-provider-dbt-cloud#82]
Same type of request as #78 

I'm primarily interested in Redshift, but according to [dbt docs the 3 stores are more or less the same](https://docs.getdbt.com/docs/dbt-cloud/cloud-configuring-dbt-cloud/connecting-your-database#connecting-to-postgres-redshift-and-alloydb)

**Comment by gary-beautypie** [comment]
Added in v0.1.4 I think, if you'd be able to test for your use case that would be much appreciated/ lmk if I missed anything 😺

**Comment by GtheSheep** [comment]
Added in v0.1.4 I think, if you'd be able to test for your use case that would be much appreciated/ lmk if I missed anything 😺

**Comment by GtheSheep** [comment]
The association has to happen separately (as happens in the UI really)

https://registry.terraform.io/providers/GtheSheep/dbt-cloud/latest/docs/resources/dbt_cloud_project_connection

**Comment by hadiel05** [comment]
tested on redshift and it's working
