### ISSUE TITLE
Add docs/ freshness job params to projects

### ISSUE THREAD

**Issue by GtheSheep** [GtheSheep/terraform-provider-dbt-cloud#98]

**Comment by b-per** [comment]
Hi! If that's ok and if you've not started working on it I might give a go at this feature.

Witht the circular dependency between **Project > Jobs (require project id)** and **Job > Project source/freshness job (require job id)**, did you have an idea on how you'd like to handle those?

Would we create a new resource called `dbt_cloud_project_artifacts` (like in dbt Cloud), and 2 optional fields:
- `freshness_job_id`
- `documentation_job_id`
![image](https://user-images.githubusercontent.com/8754100/204611288-a248e977-f6c8-49b8-b620-cfb66d81994e.png)

Or would there be a way to handle that as part of the `dbt_cloud_project` resource directly?

**Comment by GtheSheep** [comment]
Hey! Thanks for submitting, I also noticed this the other day but forgot to put an issue up 😅 haven't started working on it so a contribution would be very, very welcome!
